### ISSUE TITLE
Asking for help about the code of IIPR-Net

### ISSUE THREAD

**Issue by wdhudiekou** [Torbjorn1997/IIRP-Net#1]
I am highly intrigued by the IIPR-Net project. Are there any intentions to share the source code with the community?

**Comment by yidamyth** [comment]
Thank you for your work. Could you open source it?

**Comment by Torbjorn1997** [comment]
很抱歉之前忙于其他工作未及时更新代码，完整代码已提供。

I apologize for not updating the code in a timely manner due to other work commitments. The complete code has now been provided.
