### ISSUE TITLE
关于delta1的确定

### ISSUE THREAD

**Issue by 5ummer23** [Torbjorn1997/IIRP-Net#2]
作者你好，想请教您有关delta1的值，您在代码中设置的为0.005，请问这个值的设定是经过实验得出的最优方案还是越小越好，我尝试0.002时效果变差了

**Comment by Torbjorn1997** [comment]
我们尝试了四种相似度指标，通过在测试集上验证取值，具体可以参见补充材料的表5。实际上delta的取值与数据集和模型都有相关性，比如说在oasis数据集上iterative inference并不能取得有效的提升。
We experimented with four similarity metrics and validated their values on the test set; details can be found in Supplementary Material, Table 5. In fact, the value of delta is related to both the dataset and the model. For example, on the OASIS dataset, iterative inference does not lead to effective improvements.
![image](https://github.com/user-attachments/assets/2889fa0c-00cb-4249-925d-4e6634d56cae)

**Comment by Torbjorn1997** [comment]
此外，我们的实验是在整个测试集上测试的，对于某张特定的slice，这个选择未必是最优的，但我们认为delta的取值相对来说并非决定性因素，更大的delta带来更少的迭代次数，可以加快配准的速度。
Additionally, our experiments were conducted on the entire test set, and for a specific slice, this choice may not be optimal. However, we believe that the value of delta is not a decisive factor. A larger delta results in fewer iterations, which can accelerate the registration process.

**Comment by 5ummer23** [comment]
谢谢作者的详细回答！占用您宝贵的时间还想请教您，是否在LPBA40数据集上跑过实验，

**Comment by Torbjorn1997** [comment]
> 谢谢作者的详细回答！占用您宝贵的时间还想请教您，是否在LPBA40数据集上跑过实验，

很抱歉并没有，时间限制，我们只用了MIndBoggle和FLARE以及OASIS三个数据集。

**Comment by 5ummer23** [comment]
感谢作者，（我是新入坑的小白）您对增大特征图channel如何看待，我看您在IIRP上用的是8，16，32，32.我学习到的知识增大channel能提升效果，但是我在尝试您的模型包括其他模型时，带来的提升很小反而显存占用暴增

**Comment by Torbjorn1997** [comment]
> 感谢作者，（我是新入坑的小白）您对增大特征图channel如何看待，我看您在IIRP上用的是8，16，32，32.我学习到的知识增大channel能提升效果，但是我在尝试您的模型包括其他模型时，带来的提升很小反而显存占用暴增

根据我的经验，对于图像配准任务，增大channel并不能带来显著的提升，比如CVPR24的corrMlp就使用了很大的channel数量，但我复现并没有感觉到明显的提升，而且会爆显存。我个人认为图像配准任务对网络结构的改进以及流程的改进更有提升的空间，此外，我个人认为解码器的深度相比于编码器更重要。

**Comment by 5ummer23** [comment]
谢谢您！
