### ISSUE TITLE
Mindboggle-101数据集

### ISSUE THREAD

**Issue by 5ummer23** [Torbjorn1997/IIRP-Net#3]
作者你好，打扰您了，请问您使用Mindboggle-101数据集将其裁剪到80x96x80了吗，还是直接使用的原始大小

**Comment by Torbjorn1997** [comment]
The 3D volume for each brain scan is 160 × 192 × 160, with an isotropic voxel size of 1 mm.
做了一些裁剪，把一些没有灰度信息的区域统一裁剪掉了。

**Comment by Torbjorn1997** [comment]
MindBoggle的标签很精细，直接resample到半分辨率会有精度上的损失。

**Comment by 5ummer23** [comment]
原来是这样，我想尝试将该数据集做成pkl格式，并且改成80x96x80，dice值变得很低

> MindBoggle的标签很精细，直接resample到半分辨率会有精度上的损失。

**Comment by Torbjorn1997** [comment]
> 原来是这样，我想尝试将该数据集做成pkl格式，并且改成80x96x80，dice值变得很低
> 
> > MindBoggle的标签很精细，直接resample到半分辨率会有精度上的损失。

试模型的时候用过，我当时是nii的格式，会掉到50多。

**Comment by 5ummer23** [comment]
谢谢您！！！！

**Comment by Pull2MAX** [comment]
作者你好，能提供一下MindBoggle数据集吗
