### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by 5ummer23** [Torbjorn1997/IIRP-Net#4]
作者您好打扰您了，我跑通了您的代码，尝试跑一下mind101数据集，请问您可以分享一下大致跑了多少轮后差不多达到最优吗？我看您在设置参数时default给了1000，由于算力有限我先用了NKI-RS-22这22张尝试跑一下，恳请您指教一下训练过程中是否有不妥的地方，十分感谢！
<img width="626" alt="截屏2024-09-12 11 44 40" src="https://github.com/user-attachments/assets/f9e0c683-3df1-4a1e-a004-0fe6f594017e">

**Comment by Torbjorn1997** [comment]
看起来没什么问题，不过实际上22张实在是太少了，最好按照我们在论文中提供的配置重新分一下数据集，实际上无论数据集多大每一个epoch的step都设置成了100，所以没有任何影响。训练效果你可以看第一项的ncc loss 的收敛情况，大概200-300轮就有一个相对稳定的结果了。

**Comment by Torbjorn1997** [comment]
最优的结果我是在最后900-1000epoch里选择的验证集上效果最好的模型。

**Comment by Pull2MAX** [comment]
作者你好，我想请问一下这个mindboggle数据集的处理能不能详细说一下呢，谢谢

**Comment by Torbjorn1997** [comment]
> 作者你好，我想请问一下这个mindboggle数据集的处理能不能详细说一下呢，谢谢

不好意思之前有点忙，mindboggle的处理请参见我们的论文
We crop out the unlabeled areas in the abdomen CT scans and the background areas in the brain MRI scans. The 3D volume for each abdomen scan is 128× 128 × 96, with an isotropic voxel size of 2.5 mm. The 3D volume for each brain scan is 160 × 192 × 160, with an isotropic voxel size of 1 mm.
